// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJtQJ_Z51pv1tQi2Y0kBmQIvTw6ZcJSs',
    appId: '1:77719864454:web:a23131a10f17a5a04c3d07',
    messagingSenderId: '77719864454',
    projectId: 'test-belajar-30080',
    authDomain: 'test-belajar-30080.firebaseapp.com',
    storageBucket: 'test-belajar-30080.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB0Dnagj9_lpp2_DzFPpqtTYX41kGamoA',
    appId: '1:77719864454:android:e570fd5b8e7138734c3d07',
    messagingSenderId: '77719864454',
    projectId: 'test-belajar-30080',
    storageBucket: 'test-belajar-30080.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt5av22IWXsCppR5jFPLccHaNqQfllYMU',
    appId: '1:77719864454:ios:fc1526074045c4cd4c3d07',
    messagingSenderId: '77719864454',
    projectId: 'test-belajar-30080',
    storageBucket: 'test-belajar-30080.firebasestorage.app',
    iosBundleId: 'com.example.minggu12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt5av22IWXsCppR5jFPLccHaNqQfllYMU',
    appId: '1:77719864454:ios:fc1526074045c4cd4c3d07',
    messagingSenderId: '77719864454',
    projectId: 'test-belajar-30080',
    storageBucket: 'test-belajar-30080.firebasestorage.app',
    iosBundleId: 'com.example.minggu12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEJtQJ_Z51pv1tQi2Y0kBmQIvTw6ZcJSs',
    appId: '1:77719864454:web:b641e9a9795293024c3d07',
    messagingSenderId: '77719864454',
    projectId: 'test-belajar-30080',
    authDomain: 'test-belajar-30080.firebaseapp.com',
    storageBucket: 'test-belajar-30080.firebasestorage.app',
  );
}
